server:
  port: 3000

info:
  component: Inventory Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/api/user
  data:
      mongodb:
          host: localhost
          port: 27017
          database: microserv_inventory

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://127.0.0.1:8761/eureka/}


logging:
  level:
     org.springframework.web: DEBUG

multipart.maxFileSize: 128000KB
multipart.maxRequestSize: 128000KB
