server:
  port: 8765

info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/api/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://127.0.0.1:8761}

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    productapi: /product/**

logging:
  level:
     org.springframework.web: DEBUG
     com.netflix.zuul: DEBUG

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

